<?php
require_once 'config.php';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

$error = "";
$success = "";

// Handle Password Verification and Backup Generation
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['backup'])) {
    $password = trim($_POST['password'] ?? '');
    
    if (empty($password)) {
        $error = "Password is required to generate backup.";
    } else {
        // Verify user's password
        $stmt = $conn->prepare("SELECT password FROM users WHERE id = ? LIMIT 1");
        $stmt->bind_param("i", $_SESSION['user_id']);
        $stmt->execute();
        $result = $stmt->get_result();
        
        if ($result->num_rows === 1) {
            $user = $result->fetch_assoc();
            
            // Verify password
            if (password_verify($password, $user['password'])) {
                // Password is correct, proceed with backup
                try {
                    // Use connection from config.php
                    $conn->set_charset("utf8");

                    $tables = array();
                    $result = $conn->query('SHOW TABLES');
                    while($row = $result->fetch_row()){
                        $tables[] = $row[0];
                    }

                    $sqlScript = "-- Database Backup: " . DB_NAME . "\n";
                    $sqlScript .= "-- Generated: " . date('Y-m-d H:i:s') . "\n";
                    $sqlScript .= "-- Generated by: " . $_SESSION['username'] . " (" . $_SESSION['full_name'] . ")\n";
                    $sqlScript .= "-- User ID: " . $_SESSION['user_id'] . "\n\n";
                    $sqlScript .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

                    foreach($tables as $table){
                        // Structure
                        $result = $conn->query('SHOW CREATE TABLE ' . $table);
                        $row = $result->fetch_row();
                        $sqlScript .= "\n\n" . $row[1] . ";\n\n";
                        
                        // Data
                        $result = $conn->query('SELECT * FROM ' . $table);
                        $columnCount = $result->field_count;
                        
                        while($row = $result->fetch_row()){
                            $sqlScript .= "INSERT INTO $table VALUES(";
                            for($j=0; $j < $columnCount; $j++){
                                
                                if (isset($row[$j])) {
                                    $sqlScript .= '"' . $conn->real_escape_string($row[$j]) . '"';
                                } else {
                                    $sqlScript .= 'NULL';
                                }
                                
                                if ($j < ($columnCount - 1)) {
                                    $sqlScript .= ',';
                                }
                            }
                            $sqlScript .= ");\n";
                        }
                        $sqlScript .= "\n"; 
                    }
                    
                    $sqlScript .= "\nSET FOREIGN_KEY_CHECKS=1;";

                    if(!empty($sqlScript)){
                        // Log the backup activity
                        $log_user = $_SESSION['username'];
                        $log_action = 'Backup Database';
                        $log_desc = "Generated database backup for " . DB_NAME;
                        $log_stmt = $conn->prepare("INSERT INTO activity_logs (user, action, description) VALUES (?, ?, ?)");
                        $log_stmt->bind_param("sss", $log_user, $log_action, $log_desc);
                        $log_stmt->execute();
                        $log_stmt->close();
                        
                        $backup_file_name = DB_NAME . '_backup_' . date('Y-m-d_H-i-s') . '_by_' . $_SESSION['username'] . '.sql';
                        
                        // Clear buffer to ensure no HTML is prepended
                        if (ob_get_level()) ob_end_clean();
                        
                        header('Content-Description: File Transfer');
                        header('Content-Type: application/octet-stream');
                        header('Content-Disposition: attachment; filename=' . basename($backup_file_name));
                        header('Content-Transfer-Encoding: binary');
                        header('Expires: 0');
                        header('Cache-Control: must-revalidate');
                        header('Pragma: public');
                        header('Content-Length: ' . strlen($sqlScript));
                        
                        echo $sqlScript;
                        exit;
                    }
                } catch (Exception $e) {
                    $error = "Backup failed: " . $e->getMessage();
                    
                    // Log failed backup attempt
                    $log_user = $_SESSION['username'];
                    $log_action = 'Backup Failed';
                    $log_desc = "Database backup failed: " . $e->getMessage();
                    $log_stmt = $conn->prepare("INSERT INTO activity_logs (user, action, description) VALUES (?, ?, ?)");
                    $log_stmt->bind_param("sss", $log_user, $log_action, $log_desc);
                    $log_stmt->execute();
                    $log_stmt->close();
                }
            } else {
                $error = "Invalid password. Backup cancelled.";
                
                // Log failed authentication attempt
                $log_user = $_SESSION['username'];
                $log_action = 'Backup Auth Failed';
                $log_desc = "Backup attempt failed due to invalid password";
                $log_stmt = $conn->prepare("INSERT INTO activity_logs (user, action, description) VALUES (?, ?, ?)");
                $log_stmt->bind_param("sss", $log_user, $log_action, $log_desc);
                $log_stmt->execute();
                $log_stmt->close();
            }
        } else {
            $error = "User not found.";
        }
        
        $stmt->close();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Database Backup - <?php echo defined('SITE_NAME') ? SITE_NAME : 'BIS'; ?></title>
    
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/style.css">
    
    <style>
        .backup-container {
            max-width: 600px;
            margin: 0 auto;
            padding: 2rem;
        }
        
        .backup-card {
            background-color: var(--bg-secondary);
            border-radius: 12px;
            box-shadow: var(--shadow-md);
            padding: 3rem 2rem;
            text-align: center;
            border: 1px solid var(--border-color);
            transition: var(--color-transition);
        }
        
        .backup-icon-wrapper {
            width: 80px;
            height: 80px;
            background-color: #dbeafe;
            color: #2563eb;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 2.5rem;
            margin: 0 auto 1.5rem;
        }
        
        .backup-title {
            font-size: 1.5rem;
            font-weight: 700;
            color: var(--text-primary);
            margin-bottom: 0.5rem;
            transition: var(--color-transition);
        }
        
        .backup-description {
            color: var(--text-secondary);
            margin-bottom: 2rem;
            line-height: 1.6;
            transition: var(--color-transition);
        }
        
        .alert {
            padding: 1rem;
            border-radius: 0.5rem;
            margin-bottom: 1.5rem;
            text-align: left;
            font-size: 0.9rem;
        }
        
        .alert-danger {
            background-color: #fef2f2;
            color: #b91c1c;
            border: 1px solid #fecaca;
        }
        
        .alert-success {
            background-color: #f0fdf4;
            color: #15803d;
            border: 1px solid #bbf7d0;
        }
        
        .btn-lg {
            padding: 0.75rem 2rem;
            font-size: 1.1rem;
        }
        
        /* Modal Styles */
        .modal {
            display: none;
            position: fixed;
            z-index: 1000;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0, 0, 0, 0.5);
            animation: fadeIn 0.3s;
        }
        
        .modal.active {
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        .modal-content {
            background-color: var(--bg-secondary);
            padding: 2rem;
            border-radius: 12px;
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
            max-width: 450px;
            width: 90%;
            animation: slideIn 0.3s;
            transition: var(--color-transition);
        }
        
        .modal-header {
            display: flex;
            align-items: center;
            margin-bottom: 1.5rem;
        }
        
        .modal-icon {
            width: 50px;
            height: 50px;
            background-color: #fef3c7;
            color: #f59e0b;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 1.5rem;
            margin-right: 1rem;
        }
        
        .modal-title {
            font-size: 1.25rem;
            font-weight: 600;
            color: var(--text-primary);
            margin: 0;
            transition: var(--color-transition);
        }
        
        .modal-body {
            margin-bottom: 1.5rem;
        }
        
        .modal-text {
            color: var(--text-secondary);
            margin-bottom: 1rem;
            line-height: 1.6;
            transition: var(--color-transition);
        }
        
        .form-group {
            margin-bottom: 1rem;
        }
        
        .form-label {
            display: block;
            font-weight: 500;
            color: var(--text-primary);
            margin-bottom: 0.5rem;
            font-size: 0.9rem;
            transition: var(--color-transition);
        }
        
        .password-input-wrapper {
            position: relative;
        }
        
        .form-input {
            width: 100%;
            padding: 0.75rem 2.5rem 0.75rem 1rem;
            border: 1px solid var(--border-color);
            border-radius: 8px;
            font-size: 1rem;
            background-color: var(--bg-secondary);
            color: var(--text-primary);
            transition: var(--color-transition);
            box-sizing: border-box;
        }
        
        .form-input:focus {
            outline: none;
            border-color: #2563eb;
            box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
        }
        
        .toggle-password {
            position: absolute;
            right: 0.75rem;
            top: 50%;
            transform: translateY(-50%);
            background: none;
            border: none;
            color: var(--text-secondary);
            cursor: pointer;
            padding: 0.25rem;
            font-size: 1rem;
            transition: var(--color-transition);
        }
        
        .toggle-password:hover {
            color: var(--text-primary);
        }
        
        .modal-footer {
            display: flex;
            gap: 0.75rem;
            justify-content: flex-end;
        }
        
        .btn-secondary {
            background-color: #6b7280;
            color: white;
            border: none;
        }
        
        .btn-secondary:hover {
            background-color: #e5e7eb;
        }
        
        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
        
        @keyframes slideIn {
            from {
                transform: translateY(-50px);
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }
        
        /* Dark mode support */
        body.dark-mode .backup-card {
            background-color: #1f2937;
            border-color: #374151;
        }
        
        body.dark-mode .backup-icon-wrapper {
            background-color: rgba(37, 99, 235, 0.2);
            color: #60a5fa;
        }
        
        body.dark-mode .backup-title {
            color: #f9fafb;
        }
        
        body.dark-mode .backup-description {
            color: #9ca3af;
        }
        
        body.dark-mode .alert-danger {
            background-color: #7f1d1d;
            color: #fca5a5;
            border-color: #991b1b;
        }
        
        body.dark-mode .alert-success {
            background-color: #064e3b;
            color: #6ee7b7;
            border-color: #047857;
        }
        
        body.dark-mode .modal {
            background-color: rgba(0, 0, 0, 0.7);
        }
        
        body.dark-mode .modal-content {
            background-color: #1f2937;
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5);
        }
        
        body.dark-mode .modal-icon {
            background-color: rgba(245, 158, 11, 0.2);
            color: #fbbf24;
        }
        
        body.dark-mode .modal-title {
            color: #f9fafb;
        }
        
        body.dark-mode .modal-text {
            color: #9ca3af;
        }
        
        body.dark-mode .form-label {
            color: #f9fafb;
        }
        
        body.dark-mode .form-input {
            background-color: #111827;
            color: #f9fafb;
            border-color: #374151;
        }
        
        body.dark-mode .form-input:focus {
            border-color: #2563eb;
            box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.2);
        }
        
        body.dark-mode .toggle-password {
            color: #9ca3af;
        }
        
        body.dark-mode .toggle-password:hover {
            color: #f9fafb;
        }
        
        body.dark-mode .btn-secondary {
            background-color: #6b7280;
        }
        
        body.dark-mode .btn-secondary:hover {
            background-color: #4b5563;
        }
    </style>
</head>
<body>
    <!-- Sidebar -->
    <?php include 'components/sidebar.php'; ?>
    
    <!-- Main Content -->
    <main class="main-content">
        <!-- Header -->
        <?php include 'components/header.php'; ?>
        
        <!-- Dashboard Content -->
        <div class="dashboard-content">
            <div class="page-header-section">
                <h1 class="page-title">Database Backup</h1>
            </div>
            
            <div class="backup-container">
                <div class="backup-card">
                    <div class="backup-icon-wrapper">
                        <i class="fas fa-database"></i>
                    </div>
                    
                    <h2 class="backup-title">System Backup</h2>
                    <p class="backup-description">
                        Create a full backup of the system database. This will generate and download a SQL file containing all tables and data records.
                        <br><br>
                        <strong><i class="fas fa-shield-alt"></i> Security Notice:</strong> You will be required to enter your password to confirm this action.
                    </p>
                    
                    <?php if ($error): ?>
                        <div class="alert alert-danger">
                            <i class="fas fa-exclamation-circle"></i> <?php echo htmlspecialchars($error); ?>
                        </div>
                    <?php endif; ?>
                    
                    <?php if ($success): ?>
                        <div class="alert alert-success">
                            <i class="fas fa-check-circle"></i> <?php echo htmlspecialchars($success); ?>
                        </div>
                    <?php endif; ?>
                    
                    <button type="button" id="openBackupModal" class="btn btn-primary btn-lg">
                        <i class="fas fa-download"></i> Generate & Download Backup
                    </button>
                </div>
            </div>
        </div>
    </main>
    
    <!-- Password Confirmation Modal -->
    <div id="passwordModal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-icon">
                    <i class="fas fa-lock"></i>
                </div>
                <h3 class="modal-title">Confirm Your Identity</h3>
            </div>
            
            <div class="modal-body">
                <p class="modal-text">
                    For security purposes, please enter your password to confirm this backup operation.
                </p>
                
                <form method="POST" id="backupForm">
                    <div class="form-group">
                        <label for="password" class="form-label">
                            <i class="fas fa-key"></i> Your Password
                        </label>
                        <div class="password-input-wrapper">
                            <input 
                                type="password" 
                                id="password" 
                                name="password" 
                                class="form-input" 
                                placeholder="Enter your password"
                                required
                                autocomplete="current-password"
                            >
                            <button type="button" class="toggle-password" id="togglePassword">
                                <i class="fas fa-eye"></i>
                            </button>
                        </div>
                    </div>
                    
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" id="cancelBackup">
                            <i class="fas fa-times"></i> Cancel
                        </button>
                        <button type="submit" name="backup" class="btn btn-primary">
                            <i class="fas fa-check"></i> Confirm & Backup
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    <!-- Custom JavaScript -->
    <script src="js/script.js"></script>
    
    <script>
        // Modal functionality
        const modal = document.getElementById('passwordModal');
        const openModalBtn = document.getElementById('openBackupModal');
        const cancelBtn = document.getElementById('cancelBackup');
        const passwordInput = document.getElementById('password');
        const togglePasswordBtn = document.getElementById('togglePassword');
        
        // Open modal
        openModalBtn.addEventListener('click', function() {
            modal.classList.add('active');
            passwordInput.focus();
        });
        
        // Close modal
        cancelBtn.addEventListener('click', function() {
            modal.classList.remove('active');
            passwordInput.value = '';
        });
        
        // Close modal when clicking outside
        window.addEventListener('click', function(event) {
            if (event.target === modal) {
                modal.classList.remove('active');
                passwordInput.value = '';
            }
        });
        
        // Toggle password visibility
        togglePasswordBtn.addEventListener('click', function() {
            const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordInput.setAttribute('type', type);
            
            const icon = this.querySelector('i');
            icon.classList.toggle('fa-eye');
            icon.classList.toggle('fa-eye-slash');
        });
        
        // Close modal on Escape key
        document.addEventListener('keydown', function(event) {
            if (event.key === 'Escape' && modal.classList.contains('active')) {
                modal.classList.remove('active');
                passwordInput.value = '';
            }
        });
    </script>
</body>
</html>
